---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 3b4bbefc2df3130fa976d9b30c64b56af39f5d43
    app.quarkus.io/build-timestamp: 2022-08-30 - 09:48:42 +0000
  labels:
    app.kubernetes.io/name: account-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: account-service
spec:
  ports:
    - name: http
      nodePort: 30704
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: account-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 3b4bbefc2df3130fa976d9b30c64b56af39f5d43
    app.quarkus.io/build-timestamp: 2022-08-30 - 09:48:42 +0000
  labels:
    app.kubernetes.io/name: account-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: account-service
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 3b4bbefc2df3130fa976d9b30c64b56af39f5d43
        app.quarkus.io/build-timestamp: 2022-08-30 - 09:48:42 +0000
      labels:
        app.kubernetes.io/name: account-service
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quarkus-mp/account-service:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: account-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
